name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "triage"]
body:
    - type: markdown
      attributes:
          value: |
              We appreciate your feedback! Help us understand your needs.

    - type: input
      id: company
      attributes:
          label: Company/Organization
          placeholder: "Your company or organization"
      validations:
          required: true

    - type: input
      id: contact
      attributes:
          label: Contact Email
          placeholder: "you@company.com"
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: How important is this to you?
          options:
              - Critical (blocking us from using the product)
              - High (significant impact on our workflow)
              - Medium (nice to have)
              - Low (minor improvement)
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: What problem are you trying to solve?
          placeholder: Describe the challenge or use case
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Describe your ideal solution
          placeholder: How would you like this to work?
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives or workarounds
          placeholder: Have you tried other approaches?
      validations:
          required: false

    - type: textarea
      id: context
      attributes:
          label: Additional context
          placeholder: Any other details, mockups, or examples
      validations:
          required: false
